cameroncondry/cbc-kitten-scientists

kitten-scientists.js

This makes trading more effective and allows for off-season hunting.

Add seasons to trade

---

kitten-scientists.js

Fixes the Unicorn Pasture vs. Pasture bug, and removes the requirement to be on the Bonfire tab for building to work.

Match button labels exactly when building.

---

kitten-scientists.js

This patch modifies the game so that we no longer print messages as we
perform actions. Instead, the user may click "show activity" in the
options list in order to print a display of all actions taken by the
scientists since they last clicked it. It conveniently also shows the
previous date as well.
Possibly this might be more valuable as a listing in a display box but I
couldn't figure out how to do that.
Instead, this just allows us to condense all our output until the user
wants to see it. In this way, after long absense from the game such as
over night or several days, the user can easily see what was acomplished.

kitten-scientists: implement a simple activity system

---

kitten-scientists.js

This series includes  a few fixes requested to update the options and make things a bit more visible.
I think this is all the suggestions you had regarding interface.

minor requested enhancements to options

---

kitten-scientists.js

I just re-tested master, and I'm not sure how I missed these before. Anyways, here's a couple more cleanups for the changes.

some small fixups

---

kitten-scientists.js

This series includes support for per-resource consume rate, which defaults to the same as the generic consume rate. It also fixes up several issues with stocks and modifies display to show both consume and stock values.

implement per-resource consume rate controls

---

kitten-scientists.js

Just fixing the autunn/autumn error - see if that fixes the auto-trade problem

correct spelling error in season list

---

kitten-scientists.js

Local storage - Building, Crafting, Trading

---

kitten-scientists.js

Found three spots where I forgot to update a variable name, meaning parts of the local storage aren't working.

Corrected typo in variable name

---

kitten-scientists.js

As suggested by the v1.1.0.1 changelog ;)

Add message filters for hunts and trades

---

kitten-scientists.js

Shouldn't be able to hold a festival without Drama and Poetry

Check prerequisite tech for festivals

---

kitten-scientists.js

added header to allow use with tamper/greasemonkey
added 2 new variables to allow all fonts on page to be set to generic monospace fonts

changed all fonts on page to generic monospace fonts, including buttons

---

kitten-scientists.js

This way users can set their browsers fixed-width font to their own preference.

Change "Courier New" to `monospace` font-family

---

kitten-scientists.js

Fix typo that was fixed in game code

---

kitten-scientists.js

Allows user styles to format activities differently. (Note: Need to use !important to override the message colors.)

Add activity type classes to log messages

---

kitten-scientists.js

Exactly what it says on the tin.
Tested with latest beta.

added kerosene

---

kitten-scientists.js

Very convenient when running Kittens Game locally

Allow script to run in kitten game dev mode

---

kitten-scientists.js

Nothing is equal to NaN. Use isNaN instead.

Avoid comparison with NaN

---

.gitignore
README.md
contributors.js

mmccubbing slipped in there twice ;)

Fix duplicate contributors

---

kitten-scientists.js

More space for button text

---

kitten-scientists.js

Auto-trade now respects more button labels

---

kitten-scientists.js

Use correct substring search method

---

kitten-scientists.js

This is just a cleaned up version of #89 
I'm currently testing this change and will report if there are any problems with it. Seems to work just fine though.

Simulate click on building button

---

kitten-scientists.js

The game hides filter controls until the first message of its type. Also there's a filter for hunts by default now. Previous #89

Update message filters to match game's

---

kitten-scientists.js

Support Space tab build options

---

kitten-scientists.js

Support Sleek theme

---

kitten-scientists.js

Use internal game names for checkbox labels

---

kitten-scientists.js

I noticed that Kittens Game would be very slow to respond and consume a lot of CPU time. I analyzed which calls take up a lot of resources and optimized several paths.

Improve overall performance

---

kitten-scientists.js

Allows you to build upgraded buildings

Support later stages of buildings

---

kitten-scientists.js

Seems like I forgot to add that in my original PR

Fixed upgradeable buildings not being built

---

CHANGELOG.md
kitten-scientists.js

Prioritize housing in build order

---

kitten-scientists.user.js

Fix columns not spanning the whole page

---

kitten-scientists.user.js

This makes sure that the hunter count in the activity summary is based on the number of hunters and not on the catpower.

Fix hunter count in activity summary

---

kitten-scientists.user.js

Groups messages under date headers

Update gameLog.msg to match game

---

kitten-scientists.user.js

Fixes #171 - The game is now loaded asynchronously, which causes gamePage to not be available when the script is started.
Whole script is wrapped into run() function that is called after gamePage is available. Function loadTest does the check every 2s.

Make plugin load after gamePage is available

---

kitten-scientists.user.js

Addition of thorium autocrafting option.

Thorium Crafting

---

kitten-scientists.user.js

Because building.label is now building.meta.label

Fix buildings in 1.3.0.0

---

kitten-scientists.user.js

Add missing space buildings.

---

kitten-scientists.user.js

ks made my titanium dissapear into nowhere.
Upon closer inspection the log said ks managed to build sattelites
before i had researched sattelite technology.
They wherent even visible but i knew i had them because i was getting
starcharts from space without having ever built any space buildings.
This should fix it. I think.

Don't build space before you unlocked it.

---

kitten-scientists.user.js

This seems to fix (or at least help) with #193.

Fix hasResource() calls for kg 1.4.0.6

---

kitten-scientists.user.js

Remove console.static.msg overwrite (it's been moved to console.msg anyway)
Set max log messages to 1000 (can be higher if wanted)
Use game.msg instead of console.msg for KS messages so it automatically inserts the date header

Console changes

---

kitten-scientists.user.js

tradeMultiple(...) moved to dame.diplomacy and gets race as additional parameter

fix TradeManager.trade(...)

---

kitten-scientists.user.js

I think this shoud work. At least for me, it does.

Fix BuildManager.getBuildButton()

---

kitten-scientists.user.js

This way folks can see that they're up to date when they refresh :)

Bump version to 1.3.2

---

kitten-scientists.user.js

Missed a change that broke it. Also future proofing if a trade filter is ever actually added to the game proper.

Fix trade message filter

---

kitten-scientists.user.js

This change adds the proposed fix from #209. I did some debugging before applying the change.

Proposed fix for issue #209

---

kitten-scientists.user.js

The fix for #209 missed a comma, this little patch fixes the problem for me, and KS loads again.

Fix missing comma

---

kitten-scientists.user.js

This is an update of #168 for the latest version of the code. I haven't started a run with this enabled yet so it may have issues. I'll update once I've done that but I thought I should get it up for review before I forget.

Research Order of the Sun upgrades

---

kitten-scientists.user.js

Calculate crafting ratio correctly

---

kitten-scientists.user.js

- Realized I wasn't "continuing" the correct loop, so things were still building. Used named loops to fix that.
- Added a check for res.stock to prevent "undefined" errors in case of storage being cleared

Fix issues from last time :/

---

kitten-scientists.user.js

Complex codebase. Have to check for both res and res.stock due to how things are loaded on page load.

bugfix initial loading of stock

---

kitten-scientists.user.js

Engine toggle specifically excluded

Save top level toggles

---

kitten-scientists.user.js

- Fix Libraries not building and add Data Centers
- Remove trade filter- added in base game
- Fix ship craft prices and futureproof other craft prices
- Disable exploring by default- map feature is hidden in the game
And some things easier for external scripts
- Add html ids to options list elements
- Send an event when KS loads

Quick fixes and features

---

kitten-scientists.user.js

This adds a new menu to Kitten Scientists to manage auto-building the Time tab buildings, and has Kitten Scientists auto-build them when they meet the usual requirements. I've found these options to be pretty useful, especially when idling with a shatter engine running so higher levels of resource retrieval are automatically gained when affordable.
This was made directly in GitHub, so it seems to lack the formatting issues that my previous pull request had.

Time Tab Building Automation

---

kitten-scientists.user.js
package.json

It's been 2 years and there have been a lot of updates since, so KS is probably due for a version bump.

Version Bump to 1.3.3

---

kitten-scientists.user.js

- Remove load-breaking references to non-existent autofeed trigger
- Save autofeed toggle

Autofeed fixes

---

README.md

Rawgit is shutting down soon (or may already be dead?)

Update bookmarklet URL to jsdelivr

---

kitten-scientists.user.js

Element.toggleAttribute is pretty new, whodathunk?

Change method to set style attribute

---

CHANGELOG.md
README.md
kitten-scientists.user.js
package.json

@cameroncondry This PR has a couple of major features and a few minor changes. First, KS was starting to get too many menus so I made a new options menu and gave it trigger functionality, then moved all the options that didn't have sub-items into it. 
Second, I added a system to keep track of the resources spent and gained hunting and trading so limited trading factors these in, making it self-limiting and replacing the old arbitrary limits on it. This makes it much more capable of taking advantage of any profitable trading loops.
Third, KS can now auto build embassies in the beta branch of KG.
Fourth, automatic space missions and race discovery has been added to the upgrading tab, which has been renamed to unlocking. Upgrading buildings now has some conditions on it to prevent it from …

Options, Improved Limited Trading, Embassies, and More

---

kitten-scientists.user.js

This fixes the incorrect oil price calculation for space buildings found by @oliversalzburg in #263 as well as an edge case for cryochamber karma that would probably never come up in normal play. Caught and fixed an incorrect log output as well.

Space Oil and Cryochamber Karma Bugfixes

---

kitten-scientists.user.js

Commit [f117024](https://bitbucket.org/bloodrizer/kitten-game/commits/f11702451f8fd04250562515ba7c537fea6a392a) of the bloodrizer source code changes the `gethyperbolicEffect()` function, and renames it to `getLimitedDR()`. This change breaks the userscipt (because calls to `getHyperbolicEffect()` now fail).

Fix userscript to use new getLimitedDR() instead of getHyperbolicEffect()

---

README.md

Given that the script is compatible with the kittensgame.com version rather than the bloorizer.ru version, it would perhaps be more appropriate to link to the version that this script works with.
Perhaps the link the repo description should be updated as well?

Update README url to the new mainline

---

kitten-scientists.user.js

Script wouldn't load without it on Chrome.
Fixes issue #287

Fix scope error on i18ng

---

kitten-scientists.user.js

I try to rewrite css to make KS don't override game schemes' other css settings after "View Full Width" enabled, but failed.
CSS is too confused for me.

Make KS don't override theme font and right upgrade price

---

kitten-scientists.user.js

Fixes #302 
I am *pretty* sure I coded this right, but someone with more Javascript experience please check my work because that seemed too simple 😅

Add time boilers to Time tab

---

kitten-scientists.user.js

Adds Zebra Outpost, Zebra Workshop, and Zebra Forge

Add zebra buildings to Bonfire tab

---

kitten-scientists.user.js

d1f91acb8a77d8d84b81dfa01b3fe107506417e3 is the git commit hash
in kittens games
Closes #315

kittens game 1.4.8.4 refactor broke scripts

---

kitten-scientists.user.js

auto policy
Because the waiting time for you to merge is too long, I merge a part of the commits from https://github.com/cameroncondry/cbc-kitten-scientists/pull/319.
I am sorry for troubling you.

auto policy

---

README.md
kitten-scientists.user.js

- update readme
bug fixed:
- fixbug when job's value is 0

bugfix and update readme
