cameroncondry/cbc-kitten-scientists

kitten-scientists.js

This would add the "Auto Housing" option to automatically build huts and log houses separately from other buildings, and at a slightly higher trigger point.
Also, triggers plates before steel to see if that gets a better plates vs. steel balance.

Add Housing, Deprioritize Steel

---

kitten-scientists.js

This effectively removes the amount of catnip needed to survive a cold winter from consideration, so that the autobuild doesn't decide it needs a brand new catnip field on Autumn day 100 and kill off all the kittens.

Don't let catnip get exhausted over winter.

---

kitten-scientists.js

This enables building even when it's not the bonfireTab loaded. Do this by
ensuring we render() the bonfireTab first time we need it. Then, we can
just search the buttons list and locate the item and use the onClick()
function. This is much cleaner than having to be loaded on the bonfire tab
directly. This is similar to how automated trading is implemented.

buildManager: use internal buttons instead of loaded page

---

kitten-scientists.js

This series adds automatic trading support for zebras, and also includes some fixes from trini/cbc-kitten-scientists
The 3 patches not marked local from trini's pull are included as the first 3, with updated descriptions. I figured that was easier than trying to extract the local fixes out of that branch.
The patch series starts of with some minor changes I discovered while working, and then ends with the implementation of TradeManager and startTrades function. I separated everything out into patches as best as I could.
I believe I fixed all the major issues with use, though setting the correct defaults is something I am not certain on.
Generally, I solved the problem of multiple races by giving each race an "extra" amount to reduce total use per race. So the total amount of resource used …

Add automatic trading support

---

README.md
kitten-scientists.js

First patch adds alloy as a craftable resource. Primarily intended if we reach the titanium cap so that we don't have it capped.
Also a patch which clarifies and updates the README regarding the exact % traded as well as the new seasons improvement.

Minor update to craft list and README update

---

kitten-scientists.js

Calling .render() on the currently active tab interferes with the normal re-rendering process.

Only call .render() if we're not already on the Bonfire tab.

---

kitten-scientists.js

There are a few other small side effects to this PR, most notably that the engine is no longer enabled automatically when Kitten Scientists is loaded; the user must toggle it on.

Add option to automatically hold festivals

---

kitten-scientists.js

To prevent alloy production from completely draining the steel reserves,
add a limit so that we won't use up the steel. We probably will need some more advanced way to configure this in the future.

kitten-scientists: stock some steel

---

kitten-scientists.js

You mentioned this on a different pull request. I believe this works, it has worked so far for Faith, and I am hoping it will find a building shortly to test. I modified both Trading and Building and Festivals and the Religion options to use a new Tab object.
We should be able to extend any Tab object with whatever methods we need. For now I kept them simple. It might be worth actually incorporating more of the functionality in the tab itself, but I figured it was easier to just get the minimum tab portions there.
I tried to use a simple inheritance so that we can just do new BonfireTab() and get a handler for the Bonfire, and so forth. This should be split up evenly for convenient viewing.
It has worked successfully for both festivals, buildings, and praising. I haven't yet had it hit …

Refactor tab handling into a TabManager

---

kitten-scientists.js

I think we still have some unresolved issues here, regarding trade, since it appears to still be starving some resources. I think this might be the trigger values.
At any rate, I'm testing this, but I think it's good. No obvious problems so far.
The addition of trade-season options is very important, but I think controversial as to how they get inserted in the options list. I think it's pretty hacked on right now.
This is a rebased bit from the features optional crafting branch, with the suggested changes.

kitten-scientists: prevent over trading

---

kitten-scientists.js

Use a CraftManager to check resources for a given building, instead of the
internal function. This has the great advantage that we honor stock
limits, so that building management honors the available stocks.

buildings: use our own function to calculate available resources

---

kitten-scientists.js

Might be better to make this a text label that changes onclick, but I
couldn't see an easy way to change the label's text once it was created.
This is modeled after the trading per-seasons code. However, make it a
single checkbox, and increase the minWidth of all the options labels so
that these checkboxes always appear lined up for readability.
Also, fix the trading input.on function closure to use the passed option
instead of looking it up manually.

crafting: toggle limited field

---

kitten-scientists.js

We should ensure that stock checks work properly if the current value is
below the stock.

crafting: fix case when stock is greater than current value

---

kitten-scientists.js

During a refactor, I renamed delempty to clearunused and forgot one
location. Fix this up so the options will get displayed.

options: fix stocks mis-use of incorrect variable name

---

kitten-scientists.js

Refactor trade options to use getOption internally. This fixes a bug related to races not being toggled on the checkbox, and also reduces some code duplication which caused this bug in the first place.

trading: fix trade options for races

---

kitten-scientists.js

It is rather annoying/meaningless for consume to apply to uncapped
resources, since we will simply craft a bunch in a row. This is sort of
mitigated by the once-per-season rule, but even with this, stocks are a
much better controller for this behavior.
Instead, make consume part of "getValueAvailable" (so each caller no
longer needs to handle it), and make it only apply to resources with a max
Value.
This makes getValueAvailable smarter now as well, since it will return the
current value we will use (ie: consume) instead of just how much is
available. It also makes it better at handling non-capped resources that
have stocks, since callers of stocked resources will always get how much
is available without the weird rule that you need "2x as much as you
actually need" issue.
Since the …

crafting: make consume only apply to capped resources

---

kitten-scientists.js

This resulted in incorrectly calculating the total amount of a resource
available as being twice as much as we actually had. Very bad for
business, as you can imagine.

value: multiply by consume, not divide

---

kitten-scientists.js

The way that we cacluated the lowest amount resulted in ignoring any times
when getValue returned zero. This results in ignoring stock limits when
your available amount is below the stock. This is obviously not a good
thing.
Fix it so that we use undefined instead of 0 as the inializer check. Also,
fix getLowestTradeAmount in a similar way, though it actually seems to
have had a slightly different method to avoid this same problem. We want
to be consistent either way though.

getLowestCraftAmount: fix case where value available is 0

---

kitten-scientists.js

This pull request includes two fixes, found while testing.
a) we should be ensuring that we store the internal name for resources, so that we always use the same name. This is true rather than using the newer name, since "Time crystal" is the title for "TimeCrystal" and has a space, which might upset the javascript code.
In addition, we need to be sure to use the right stock so that compendium actually gets stocks applied.
b) the second patch is a fix for limited-season crafting. We were previously storing the season even if we couldn't actually craft any. This potentially resulted in us accidentally stopping all crafts for longer than we should have, by starting to block a season even though we didn't actually craft any.

stocks: display title if available but use internal name

---

kitten-scientists.js

This patch fixes a typo of the use of allowuncapped instead of
allowcapped. This should (properly) fix leviathan trade.
Fixes: fdc6f02 ("issue #49: allow leviathans to trade even when capped")

trade: fix issue #61 leviathans trade

---

kitten-scientists.js

In the rare case that wood is nearly at cap, prevent the scientists from
producing so much wood that we actually lose any. We should produce enough
to keep catnip from overflowing, while then nearly imemdiately crafting
wood into beams. This helps prevent a small loss in efficiency.

crafting: prevent kittens from over-crafting wood

---

kitten-scientists.js

Correcting obtainium spelling for eludium and chronosphere 'require' that was preventing automated activities.

Obtainium spelling correction

---

kitten-scientists.js

Buildings most generally want to be build even if it would consume more than
the 0.6 default amount. Add an "all" parameter, which will default to undefined
(false-y) and only set it to true for buildings. This should enable buildings
even if it would cost more than 60% of the available resources.

buildings: ignore consumption rate

---

kitten-scientists.js

Prevent spamming the log in iron will mode (and early normal mode?
when trying to hunt with low maximum catpower by adding a direct check
on the current catpower value.
For reference, my log every time my catpower reaches 60 (in iron will mode, with 1 zebra) is this:
> Sent 100 kittens on the hunt
> Sent 99.000 kittens on the hunt
> Sent 97.500 kittens on the hunt
> Sent 96.000 kittens on the hunt
> *(20 lines removed)*
> Sent 64.650 kittens on the hunt
> Sent 63.150 kittens on the hunt
> Sent 61.650 kittens on the hunt
> Sent 60.150 kittens on the hunt

Add catpower value check to hunting

---

kitten-scientists.js

I was getting this error, probably due to some extension that is filtering stuff out of the page:
`Uncaught IndexSizeError: Failed to execute 'insertRule' on 'CSSStyleSheet': The index provided (1) is larger than the maximum index (0).`
It seems like the script will keep working for everyone else.

Fix CSS insert crash

---

kitten-scientists.js

I found the TODO and decided to act on it. This change checks the game.calendar object. If `game.calendar.observeBtn` is defined, there exists a button that can be pressed on the interface. 
Calling `game.calendar.observeHandler()` will trigger star observation and get rid of the button.
I wrote an alternative way to observe stars that adds a observer (using `Object.observe()`) to game.calendar to check for the update to `game.calendar.observeBtn`, but `game.calendar` gets updated about 10 times a tick, so sticking with Kitten Scientists' polling method may be superior, particularly for slow computers... but I figured it was worth sharing in case someone has considered changing Kitten Scientists to be event-based rather than polling. That branch can be seen here: …

Bypass interface to observe stars

---

kitten-scientists.js

Buildings that can be upgraded have multiple labels, we generally want the label from the first stage.
Closes #95

Fix auto-build for upgradable buildings

---

kitten-scientists.js

This fixes multiple issues with the given line.
1. The quotes are invalid syntax, thus, making the whole rule void.
2. `10px` is too small IMHO
3. Without `!important`, the game will selectively apply `font-size: 90%` as an inline style to the buttons of building that can be toggled. This results in buttons having different heights and that just looks horrible!

Fix font size

---

kitten-scientists.js

`self` is a reference to the root element (`window`) and `game` points to a DOM element. That is not what is needed here. We actually want a different `game` object, which is directly accessible.
The `getEffect` call would cause an exception to be thrown and trading would never happen.
Additionally, we now bail out early if no trade is possible.

Fix auto-trading no longer working

---

kitten-scientists.js

The "Engine" checkbox is not intuitively recognized as required to be checked for the scientists to go to work. A clearer label for the checkbox will improve the user experience for new users.

Clarify engine toggle

---

kitten-scientists.js

The scientists can reference resources which aren't actually available in the version of the game that is being played. This change safeguards against that situation by avoiding access to undefined members.

Safeguard against resources that aren't available

---

kitten-scientists.js

This makes it clear that the script is loaded and has the added benefit of being able to jump into the VM source in Chrome.

Add log message when KS is loaded

---

CHANGELOG.md
kitten-scientists.js

Adds a new button to the user interface, which, when clicked, allows the user to set a new trigger threshold for an auto section.
It's possible that I have to rebase this if #137 is merged, because the additions to `CHANGELOG` probably creates a merge conflict.
I also think that the way storage and UI creation is handled needs a makeover. I'll also try to uncrowd the UI a little bit after this is merged.

Allow the user to configure the trigger threshold

---

kitten-scientists.js

The script file was renamed to better interact with userscript managers. Users with the bookmarklet would still reference the old file name. I attempted to solve that by using a symlink, but GitHub will not provide the raw content for a symlinked file, which would make the bookmarklet fail.

Show a message to users using the old script URL

---

kitten-scientists.user.js

We have a user configurable trade ratio but this is only checked for gold
and not the trade item itself.  In most cases this is fine as we'll be
above both ratios normally.  However for Leviathans we're unlikely to be
close enough to the trigger in Unobtanium and thus won't trade in that
short window.

Trade: Remove per race trigger

---

kitten-scientists.user.js

This modifies the buildings, crafts, and trading messages in `displayActivitySummary` to use the past tense, fixing #157.

Use past tense for all activity summaries

---

kitten-scientists.user.js

This modifies the `hunt()` function so that it looks up `game.village.getJob('hunter').value` instead of `game.getDisplayValueExt(catpower.value)` when recording hunts in the activity log, fixing #154.  The word "kittens" is correctly singularized when only one hunter is available.

Show number of kittens sent to hunt, not catpower

---

package.json

Since I bumped the version in kitten-scientists.user.js before. Well if we want to bump the version - but seems like a good idea when it supports a new version of Kittens Game

The version should also be bumped to 1.3.1 in package.json

---

kitten-scientists.user.js

The new styling of checkboxes on 1.3.0.0 is done by a css hack that assigns the image to a ::before element of the label for checkboxes. So without a label nothing is shown. So this just adds an empty label after the checkbox.

Fix display of Show activity checkbox on 1.3.0.0

---

kitten-scientists.user.js

renderFilters is now part of game.ui, was causing TypeError on start.
See this reddit thread:
https://www.reddit.com/r/kittensgame/comments/62r8nq/kitten_scientists_wont_start_typeerror_message/

Corrected crash on start due to renderFilters move

---

kitten-scientists.user.js

Missed this part of the console.msg override, KS activity messages can have multiple types (like praising). This in effect sets the log element's className like it did before, and still without needing to override the game's methods.

Fix multi-type activity messages

---

kitten-scientists.user.js

Furs and unobtainium wouldn't load their stock/consume settings from localStorage since their list elements existed already.

Always load craft settings over defaults

---

kitten-scientists.user.js

The previous fix for #209 more or less solved the problem but sort of by accident. When the game first starts `festivalBtn` still doesn't exist so we trigger the same error. Eventually the game creates the button and the problem goes away. This change forces the tab to render so the button is always available.

Ensure tab has rendered so we can click button

---

kitten-scientists.user.js

As noted in #173 for a while now when the script is enabled buttons in the game stop updating normally. I had previously discovered this was caused by the calls to render the tabs (needed to make sure the buttons exist to click on) but was unable to figure out why. After #213 this started happening to the kitten assignment buttons in the village tab too so I took another look at it. Turns out the problem was pretty simple, the activeTabId variable moved so we were always rendering tabs rather than only when they weren't the active one. This should also give a small performance improvement since we're not doing useless work.

Check correct location for active tab id

---

kitten-scientists.user.js

I finally got a chance to do a reset and watch the religion code in action. Turns out, it doesn't work. The logic for storing the button's label has changed, this changes the ReligionManager to match the BuildingManager logic so it can find the buttons to click on.

Update logic for getting religion buttons

---

kitten-scientists.user.js

During the "Winter Has Come" challenge the calendar display name is always "Winter". This causes the limited crafting option to never craft things as the season doesn't change. If we instead use the season ID this will work in all situations as that still goes from 0 to 3 like normal.

Use season id for limited crafting

---

kitten-scientists.user.js

This patch stems from my annoyance at KS using my stockpiled resources for buildings. This adds a check that makes buildings respect the resource "stock" settings. I verified that it worked, if there are other unit tests or whatever that should be examined as well then please let me know how to do that.

add check to stock settings before building

---

kitten-scientists.user.js

Had an issue recently where nothing was crafting, turned out to be due to my resource stock settings set way to high from a previous reset. This highlights whenever stock is higher than maxValue. Maybe someone else had this issue, figured I'd send it back up the chain.

add visual warning when stock > max resource cap

---

kitten-scientists.user.js

The addition of checking building prices is causing errors with second-stage buildings because they do not have direct entries in the game's data.

Fix building price checking with building stages

---

kitten-scientists.user.js

Hi everybody !
This pull request introduces a different approach to the "Limited" flag in automatic crafting.
So, my understanding of this option is that we want to limit the consumption of resources used in crafting, so that we can still have some of the original resource (example : I want to automatically craft scaffolds, but still have some beams for other uses)
The current system limits to one craft per season, which is not really efficient.
My proposal is to remove any dependency to time, and instead, only rely on the craft ratio and current amounts of each material, to maintain them in "equal" proportions.
For example, knowing that the conversion ratio is 50 beam -> 1 scaffold, if we enable the scaffold crafting with the "limited" flag, here is what would happen : 
|beam …

WIP : Modification of the "limited" flag on crafting

---

kitten-scientists.user.js

- Ties the changes to a data attribute on the body for easy toggling
-- The game overwrites all css classes on body when you change themes, so can't use that
- Better handle sleek theme- rules are set regardless of your theme on load, but most are inactive while you are on sleek
There are some minor visual changes compared to before, probably due to inline vs stylesheet and/or specificity changes, but on my screen it's almost the same
There is no interface for toggling the changes (yet?), all my ideas towards that involve some hack or another to fit them into how the layout is built now :/

Use stylesheet rules for CSS changes

---

kitten-scientists.user.js

Added automation options for building all Ziggurat and Cryptotheology buildings in the Religion tab along with Molten Core in the Space tab. Currently the unicorn building automation isn't super useful as it just buys the cheapest as usual, though this might be nice for longer idling sessions.

Religion Functionality, also Molten Core

---

kitten-scientists.user.js

I've implemented a cost ratio calculation into the limited crafting system as suggested in #222 so the system now actually produces an appreciable amount of the secondary crafted resources when later in the game. Also updated documentation and the toggle message to reflect the current state of the limited crafting system, since it hasn't been based on season for almost 2 years.

Making Limited Crafting Make Sense

---

kitten-scientists.user.js

I found the cause of the long-standing enable-all bug, where clicking enable-all would enable everything but then instantaneously disable it referenced in #155 , #160 , and possibly #159. It appears that the cause was that enabling used .is() while disabling used .not(), and while .is() leaves the property intact, .not() deletes it if it finds it. The enable-all and disable-all buttons would call these twice at one point, so clicking enable-all would have .not(':checked') return false, delete the 'checked' property, then .not(':checked') would return true and it would toggle the buildings off. At least that is my understanding of what was going on. Regardless, changing the input.not() to !input.is() fixed the issue.

Fixing The Enable-All Button/At least one Trade Error

---

kitten-scientists.user.js

This is a new menu that allows KS to automatically research available technologies and workshop upgrades when it has the necessary resources. Furthermore, it also has an option to automatically upgrade buildings when possible (such as amphitheatres to broadcast towers) skipping the usual confirmation prompt. 
These settings are particularly useful when frequently resetting to farm paragon using chronospheres, since as soon as KS builds one library, it will instantly purchase all techs if enough resources were carried over, and as soon as it builds a workshop, it will do the same for workshop upgrades. Though these could be useful for more early game players if they want to purchase techs and workshop upgrades whenever possible.

Automated Research, Workshop Upgrades, and Building Stage Upgrades

---

kitten-scientists.user.js

I completely overhauled the automated building for the bonfire tab to be able to build more than a single building at a time. Now it instead it creates a temporary copy of the resource pool, and iterates through the array of possible buildings, subtracting the resource cost from the fake resource pool if possible to build an additional building of this type with the remaining resources and increasing the "to be built" number of this building by one, and removing the building from the array if no longer possible. This means that no building will be underrepresented by the system. All the usual conditions need to be met for a building to actually fall into the possible buildings array, enabled and trigger and actually being unlocked and etc.
The actual build manager has been modified …

Bulk Building, an Overhaul of Automated Building

---

kitten-scientists.user.js

This pull request is a collection of a handful of minor modifications to the crafting system to make limited crafting a bit more versatile.
Firstly, in the current version of KS, the limited toggle has no effect for resources made with only raw resources (such as slabs or plates). The reason for this is that the trigger and consumption rate took priority over limited crafting, so it would always wait until the trigger is reached before consuming the consumption rate in raw resources thus causing the limited toggle to have no effect. I've changed it so that limited crafting now takes priority over these, so that regardless of the storage cap, KS will for example turn 500 minerals into 250 minerals and 1 slab. Once the trigger value is reached or if limited is disabled for these resources, …

Some Crafting/Trade Improvements and A Bulk Build Bugfix

---

kitten-scientists.user.js

The buyEcoin function name has changed to buyBcoin in the nightly stable build in kittens game.  This change works in both the main kittens game stable official mainline version and the stable nightly build.
closes #276

buyEcoin function name changed in v 1.4.8.0

---

kitten-scientists.user.js

This PR adds support for the new Brewery building, allowing KS to autocraft it when enabled. It's disabled by default.
Brewery is currently only available on beta. I **think** this degrades elegantly on main (the building will appear in the Bonfire list, but won't do anything even if enabled) but I haven't been able to test comprehensively.

Add Brewery to supported buildings.

---

kitten-scientists.user.js

The styling that kitten scientists applies to the game does not always work well with every theme. This PR allows the user to turn off this styling while still maintaining the styling for the ks menu.

Make the kitten scientist style optional with a toggle

---

kitten-scientists.user.js

Fixes issue #289 and issue #286. Tested and seems to be functioning without any problems. Can set the trigger to any amount and resources will be crafted when available, including manuscripts.

Fixed manuscript crafting by pulling from the game's actual prices. 

---

kitten-scientists.user.js

This should automatically load Kitten Scientists on the alpha and beta versions of Kittens Game. Previously, you had to manually include the URL's in Tampermonkey/Greasemonkey to made KS load with the alpha and beta versions.

Load KS automatically with alpha and beta versions of KG with Tampermonkey/Greasemonkey

---

kitten-scientists.user.js

The input parameter type of the game.getResCraftRatio() function should be a string. In some calls of scientists, the parameter passed in is craft, which causes getResCraftRatio to return only the basic radio, that is, workshop, leader, etc. For the blueprint, the input parameter type is wrong so the CAD system radio is not added. However, it does not affect the final production quantity, only the number of records in the log.

Fix a bug where the actual number of blueprints made by scientists and the number shown in the log do not match

---

README.md
kitten-scientists.user.js

new functions:
- add missions subTrigger
- add ignore some upgrades
- add make leader
bug fixed:
- when catpower's' tickval very large(or time skip got catpower), "hunt" function and "trade" function enabled together,but only "hunt" function worked. So delay hunt function.
- auto hunt disabled when during the pacifism challenge
- fix "getPotentialCatnip"
- fix when timeCrystal less than Combust Tc Prices will continue timeCtrl function
- add "trade Blcakcoin" function condition
- fix spacing
- Fix "fix Cryochamber" function check resources.
- fix unobtainium carfting to eludium
- religion upgrades right prices under leader effect
- embassy right prices under cost reduction policies and during the pacifism challenge
- add upgrade building condition

add unlocking subtrigger and limited

---

kitten-scientists.user.js

game.diplomacy.get("zebras").sells no longer contains titanium hence change the logic the always recalculate titanium value for zebras

fix zebra trade

---

kitten-scientists.user.js

new:
-  policy function skip confirm
- game's function replace onclick in upgradeManager 
- add on all reactor bld when uranium ticks > 0
bug fixed:
- fix distribute bug
- fix crypto logic
- fix zebras trade factor
- fix policy blocked logic
Minor:
- should better for craft to steel or plate when limited and don't want another item.
- trade will keep 100 manpower for keep fasthunter button (layout will not shift)
- add var、semicolon

policy skip confirm
